package mobilitydetection.hdm.kk104.com.mobilitydetectionlibrary.constants;

public class Actions {

    public static String SAVE_DATA_ACTION = "SAVE_DATA_ACTION";
    public static String LOCATION_ACTION = "LOCATION_ACTION";
    public static String ACTIVITY_DETECTED_ACTION = "ACTIVITY_DETECTED_ACTION";
    public static String ACTIVITY_VALIDATED_ACTION = "ACTIVITY_VALIDATED_ACTION";
    public static String VALIDATE_ACTIVITY_ACTION = "VALIDATE_ACTIVITY_ACTION";
    public static String ACTIVITY_TRANSITIONED_ACTION = "ACTIVITY_TRANSITIONED_ACTION";
    public static String ACTIVITY_TRANSITIONED_RECEIVER_ACTION = "ACTIVITY_TRANSITIONED_RECEIVER_ACTION";
    public static String ACTIVITY_TRANSITIONS_LOADED_ACTION = "ACTIVITY_TRANSITIONS_LOADED_ACTION";
    public static String ACTIVITY_LIST_ACTION = "ACTIVITY_LIST_ACTION";
    public static String STOP_MOBILITY_DETECTION_ACTION = "STOP_MOBILITY_DETECTION_ACTION";
    public static String POWER_CONNECTION_ACTION = "POWER_CONNECTION_ACTION";
    public static String WIFI_CONNECTION_ACTION = "WIFI_CONNECTION_ACTION";
    public static String GEOFENCE_TRANSITION_ACTION = "GEOFENCE_TRANSITION_ACTION";
    public static String GEOFENCE_ADDED_ACTION = "GEOFENCE_ADDED_ACTION";
    public static String GEOFENCE_REMOVED_ACTION = "GEOFENCE_REMOVED_ACTION";
    public static String GEOFENCES_REMOVED_ACTION = "GEOFENCES_REMOVED_ACTION";

}
